### ISSUE TITLE
American to British not working

### ISSUE THREAD

**Issue by robinzimmer1989** [HoldOffHunger/convert-british-to-american-spellings#1]
Hi there,

I've tried out your tool and everything is working fine for translations from British to American but not vice-versa. 

The following error is thrown out:

Warning: preg_replace(): Parameter mismatch, pattern is a string while replacement is an array in /.../multilingual/AmericanBritishSpellings.php on line 45

Warning: ucwords() expects parameter 1 to be string, array given in /.../multilingual/AmericanBritishSpellings.php on line 47

I want to use the tool for filtering wordpress content:

function replace_content($content){

  $args = array(
    'text'=>$content
  );

  $american_british_spellings = new AmericanBritishSpellings($args);
  $content = $american_british_spellings->SwapAmericanSpellingsForBritishSpellings($args);

  return $content;
}
add_filter('the_content','replace_content');

Thanks in advance for your help!

Best regards
Robin

**Comment by HoldOffHunger** [comment]
Hey, hey,

Sorry about that.  That would be a mistake, just fixed it now.

Issue was that there are multiple, British variants, which stored as an Array create that problem.  Resolved.

**Comment by robinzimmer1989** [comment]
Hi, thank you for your help! But for some reason it still doesn't work.
I edited the code to the following and now everything is working fine:

public function SwapAmericanSpellingsForBritishSpellings($args) {
	$text = $args['text'];
	$spelling_alternatives = $this->GetAmericanToBritishSpellings();

	foreach($spelling_alternatives as $american_spelling => $british_spelling) {
		if(!is_array($british_spelling)) {
			$text = preg_replace('/\b' . $american_spelling . '\b/', $british_spelling, $text);

			$uppercased_british_spelling = ucwords($british_spelling);
			if($uppercased_british_spelling != $british_spelling) {
				$uppercased_american_spelling = ucwords($american_spelling);

				$text = preg_replace('/\b' . $uppercased_american_spelling . '\b/', $uppercased_british_spelling, $text);
			}
		}
	}

	return $text;
}

**Comment by HoldOffHunger** [comment]
Sorry about that, you're right, it was still broken. =\

Your fix will ignore British equivalents when there are multiples, though.  This fix I just did should handle it:

			foreach($spelling_alternatives as $american_spelling => $british_spelling) {
				if(is_array($british_spelling)) {
					$british_spelling = $british_spelling[0];
				}
				
				$text = preg_replace('/\b' . $american_spelling . '\b/', $british_spelling, $text);
				
				$uppercased_british_spelling = ucwords($british_spelling);
				if($uppercased_british_spelling != $british_spelling) {
					$uppercased_american_spelling = ucwords($american_spelling);
					
					$text = preg_replace('/\b' . $uppercased_american_spelling . '\b/', $uppercased_british_spelling, $text);
				}
			}

**Comment by robinzimmer1989** [comment]
Hi thank you so much for your suppport.

Now everything is working fine!

 

Best regards

Robin

 

Gesendet: Dienstag, 09. Januar 2018 um 14:47 Uhr
Von: HoldOffHunger <notifications@github.com>
An: HoldOffHunger/convert-british-to-american-spellings <convert-british-to-american-spellings@noreply.github.com>
Cc: robinzimmer1989 <robinzimmer1989@web.de>, "State change" <state_change@noreply.github.com>
Betreff: Re: [HoldOffHunger/convert-british-to-american-spellings] American to British not working (#1)


Sorry about that, you're right, it was still broken. =\

Your fix will ignore British equivalents when there are multiples, though. This fix I just did should handle it:

		foreach($spelling_alternatives as $american_spelling => $british_spelling) {
			if(is_array($british_spelling)) {
				$british_spelling = $british_spelling[0];
			}
			
			$text = preg_replace('/\b' . $american_spelling . '\b/', $british_spelling, $text);
			
			$uppercased_british_spelling = ucwords($british_spelling);
			if($uppercased_british_spelling != $british_spelling) {
				$uppercased_american_spelling = ucwords($american_spelling);
				
				$text = preg_replace('/\b' . $uppercased_american_spelling . '\b/', $uppercased_british_spelling, $text);
			}
		}
